export const icons = {
  arrows: {
    up: '↑',
    down: '↓',
    left: '←',
    right: '→',
    blockRight: '⊳',
    blockLeft: '⊲',
    rightChevron: '›',
    rightDoubleChevron: '»',
  },
  context: '⑆',
  thinking: '⚼',
  cache: '⛁',
  time: '⌛',
  speed: '↯',
  tool: '⯿',
  git: '⑂',
  prompt: '❱',
  check: '✓',
  cross: '✗',
  edit: '✎',
  play: '⏵',
  collapse: '┏',
  tree: {
    branch: '├─',
    last: '└─',
  },
}