export const icons: Record<string, string> = {
  // Status
  success: "✓",
  cross: "✗",
  error: "✘",
  warning: "▲",
  info: "ℹ",
  question: "?",
  pending: "◌",
  running: "◐",
  bullet: "•",
  circle: "●",
  outlineCircle: "○",
  square: "■",
  outlineSquare: "□",
  diamond: "◆",
  outlineDiamond: "◇",
  star: "★",
  outlineStar: "☆",
  heart: "♥",
  checkSquare: "☑",
  uncheckedSquare: "☐",
  clock: "◷",
  hourglass: "⌛",
  pin: "⍟",

  // Arrows & navigation
  arrowLeft: "←",
  arrowRight: "→",
  arrowUp: "↑",
  arrowDown: "↓",
  arrowUpDown: "↕",
  arrowLeftRight: "↔",
  arrowUpRight: "↗",
  arrowDownRight: "↘",
  arrowUpLeft: "↖",
  arrowDownLeft: "↙",
  chevronLeft: "‹",
  chevronRight: "›",
  chevronUp: "˄",
  chevronDown: "˅",
  doubleArrowRight: "»",
  doubleArrowLeft: "«",
  promptBig: "❯",
  enter: "⏎",
  send: "➤",
  tab: "⇥",
  escape: "⎋",
  backspace: "⌫",
  command: "⌘",
  shift: "⇧",
  control: "⌃",
  option: "⌥",
  capsLock: "⇪",
  space: "␣",

  // Files & folders
  folder: "▸",
  folderOpen: "▾",
  file: "≡",
  fileText: "▤",
  fileConfig: "⚙",
  fileArchive: "▣",
  fileImage: "▨",
  symlink: "↪",
  bookmark: "⚐",
  collapse: "▾",
  uncollapse: "▸",

  // Git & diff
  gitBranch: "⑂",
  gitMerge: "⌥",
  gitCommit: "⊙",
  gitCompare: "⇄",
  gitStash: "⊟",
  diffAdded: "+",
  diffRemoved: "−",
  diffModified: "±",
  diffRenamed: "→",
  conflict: "≠",

  // Edit operations
  add: "+",
  remove: "−",
  edit: "✎",
  save: "⌸",
  copy: "⎘",
  cut: "✂",
  undo: "⟲",
  redo: "⟳",
  search: "⌕",
  replace: "⇄",
  filter: "≣",
  sort: "⇅",
  refresh: "↻",
  sync: "⇋",
  eye: "◉",
  eyeClosed: "◌",
  flag: "⚑",
  bell: "♪",
  gear: "⚙",
  wrench: "⚒",
  hammer: "⚒",
  plug: "⌁",
  power: "⏻",
  key: "⚿",
  shield: "⛨",
  link: "⌗",

  // Chat & AI
  robot: "⌬",
  human: "☺",
  thought: "…",
  tool: "⋊",
  stop: "⏹",
  pause: "⏸",
  play: "⏵",
  skip: "⏭",
  record: "⏺",
  cost: "$",
  usage: "▤",

  // Boxes, borders & layout
  boxTopLeft: "┌",
  boxTopRight: "┐",
  boxBottomLeft: "└",
  boxBottomRight: "┘",
  boxHorizontal: "─",
  boxVertical: "│",
  boxCross: "┼",
  boxHeavyHorizontal: "━",
  boxHeavyVertical: "┃",
  ellipsis: "…",
  verticalEllipsis: "⋮",
  horizontalEllipsis: "⋯",
  middleDot: "·",
  caretUp: "▲",
  caretDown: "▼",
  caretLeft: "◀",
  caretRight: "▶",

  // Bars & progress
  blockFull: "█",
  blockLight: "░",
  blockMedium: "▒",
  blockHeavy: "▓",
  upperHalf: "▀",
  lowerHalf: "▄",
  progressFull: "█",
  progressEmpty: "░",

  // Math & misc
  plus: "+",
  minus: "−",
  multiply: "×",
  divide: "÷",
  equals: "=",
  notEquals: "≠",
  greaterOrEqual: "≥",
  lessOrEqual: "≤",
  approximately: "≈",
  infinity: "∞",
  lambda: "λ",
  hash: "#",
  at: "@",
  asterisk: "✱",
}
