/** Life-motivational micro-phrases shown while the model is executing.
 * One is picked at random per run (see `ThinkingIndicator`). */
export const MOTIVATIONAL_PHRASES: readonly string[] = [
  "Every line of code is a step forward.",
  "Small steps still move mountains.",
  "Progress loves persistence.",
  "Great things are built one commit at a time.",
  "Stay curious — the best is yet to come.",
  "Your future self is cheering for you.",
  "Mistakes are proof that you are trying.",
  "Focus is a superpower. Use it wisely.",
  "Every problem is a puzzle waiting to be solved.",
  "Done is better than perfect — and perfect starts with done.",
  "Consistency beats intensity.",
  "You are closer than you think.",
  "The hardest part is starting. You already did.",
  "Growth happens outside the comfort zone.",
  "One small win today beats ten tomorrow.",
  "Trust the process, then improve it.",
  "Breathe. You have solved harder things.",
  "Effort compounds like interest.",
  "Show up today. That is the whole secret.",
  "A journey of a thousand miles begins with a single step.",
  "Fall seven times, stand up eight.",
  "Slow progress is still progress.",
  "You do not have to be great to start, but you have to start to be great.",
  "Discipline is choosing what you want most over what you want now.",
  "The best time to plant a tree was yesterday. The second best is now.",
  "Stars can't shine without darkness.",
  "Your only limit is the one you keep defending.",
  "Dream big. Start small. Act now.",
  "Success is the sum of small efforts repeated daily.",
  "You miss every shot you do not take.",
  "Be stronger than your strongest excuse.",
  "Doubt kills more dreams than failure ever will.",
  "Little by little, a little becomes a lot.",
  "The obstacle is the way.",
  "What you do every day matters more than what you do once in a while.",
  "Energy flows where attention goes.",
  "Make peace with your past so it does not spoil your present.",
  "It always seems impossible until it is done.",
  "Do something today that your future self will thank you for.",
  "You are allowed to be both a masterpiece and a work in progress.",
  "Small daily improvements are the key to staggering long-term results.",
  "Courage is not the absence of fear, but moving forward with it.",
  "Comparison is the thief of joy. Run your own race.",
  "The expert in anything was once a beginner.",
  "Difficult roads often lead to beautiful destinations.",
  "Do not count the days. Make the days count.",
  "A river cuts through rock not because of power, but persistence.",
  "Your potential is endless. Your excuses are optional.",
  "Wake up with determination, go to bed with satisfaction.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Sometimes later becomes never. Do it now.",
  "The key to success is to focus on goals, not obstacles.",
  "Believe you can, and you are halfway there.",
  "Do not watch the clock. Do what it does — keep going.",
  "Everything you have ever wanted is on the other side of consistency.",
  "Be the energy you want to attract.",
  "Well done is better than well said.",
  "It never gets easier. You just get stronger.",
  "Motivation gets you going, but habit keeps you growing.",
  "The secret of getting ahead is getting started.",
  "If it does not challenge you, it will not change you.",
  "Quality is not an act, it is a habit.",
  "Keep your eyes on the stars and your feet on the ground.",
  "You are capable of more than you know.",
  "Turn your wounds into wisdom.",
  "What we think, we become.",
  "Simplicity is the ultimate sophistication.",
  "First, solve the problem. Then, write the code.",
  "Simplicity is the soul of efficiency.",
  "Make it work, make it right, make it fast.",
  "Perseverance is not a long race. It is many short races one after the other.",
  "Do the hard things while they are still easy.",
  "A calm mind brings inner strength and self-confidence.",
  "The best way out is always through.",
  "Fortune favors the bold.",
  "He who has a why to live can bear almost any how.",
  "Turn the page. Do not close the book.",
  "Even the tallest tower started below the ground.",
  "Seeds grow in the dark before they see the light.",
  "You are not behind. You are on your own timeline.",
  "Storms make trees take deeper roots.",
  "Smooth seas never made a skilled sailor.",
  "The climb is hard because the view is worth it.",
  "Progress is not loud. It is quiet, steady work.",
  "Rest if you must, but do not quit.",
  "A goal without a plan is just a wish.",
  "You cannot go back and start over, but you can start now.",
  "Fear is temporary. Regret lasts forever.",
  "Strength grows in the moments you think you cannot go on.",
  "Every accomplishment starts with the decision to try.",
  "You are building something worth building.",
  "Slow is smooth, and smooth is fast.",
  "The days are long but the years are short. Make today matter.",
  "Whatever you are, be a good one.",
  "Light tomorrow with today.",
  "Do not wait for opportunity. Create it.",
  "Great oaks from little acorns grow.",
  "One day or day one. You decide.",
];

/** Pick one phrase at random — called once per execution so each run shows a
 * different line. */
export function pickMotivationalPhrase(): string {
  return MOTIVATIONAL_PHRASES[Math.floor(Math.random() * MOTIVATIONAL_PHRASES.length)] ?? "";
}
