// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file

import { resolveBundledFilePath } from "@opentui/core"
import type { FiletypeParserOptions, InjectionMapping } from "@opentui/core"

interface FileImportModule {
  readonly default: string
}

const bundledAssetLoaders: Record<string, () => Promise<FileImportModule>> = {
  "python/highlights.scm": () => import("./python/highlights.scm" as string, { with: { type: "file" } }),
  "python/tree-sitter-python.wasm": () => import("./python/tree-sitter-python.wasm" as string, { with: { type: "file" } }),
  "rust/highlights.scm": () => import("./rust/highlights.scm" as string, { with: { type: "file" } }),
  "rust/tree-sitter-rust.wasm": () => import("./rust/tree-sitter-rust.wasm" as string, { with: { type: "file" } }),
  "go/highlights.scm": () => import("./go/highlights.scm" as string, { with: { type: "file" } }),
  "go/tree-sitter-go.wasm": () => import("./go/tree-sitter-go.wasm" as string, { with: { type: "file" } }),
  "cpp/highlights.scm": () => import("./cpp/highlights.scm" as string, { with: { type: "file" } }),
  "cpp/tree-sitter-cpp.wasm": () => import("./cpp/tree-sitter-cpp.wasm" as string, { with: { type: "file" } }),
  "csharp/highlights.scm": () => import("./csharp/highlights.scm" as string, { with: { type: "file" } }),
  "csharp/tree-sitter-c_sharp.wasm": () => import("./csharp/tree-sitter-c_sharp.wasm" as string, { with: { type: "file" } }),
  "bash/highlights.scm": () => import("./bash/highlights.scm" as string, { with: { type: "file" } }),
  "bash/tree-sitter-bash.wasm": () => import("./bash/tree-sitter-bash.wasm" as string, { with: { type: "file" } }),
  "c/highlights.scm": () => import("./c/highlights.scm" as string, { with: { type: "file" } }),
  "c/tree-sitter-c.wasm": () => import("./c/tree-sitter-c.wasm" as string, { with: { type: "file" } }),
  "java/highlights.scm": () => import("./java/highlights.scm" as string, { with: { type: "file" } }),
  "java/tree-sitter-java.wasm": () => import("./java/tree-sitter-java.wasm" as string, { with: { type: "file" } }),
  "kotlin/highlights.scm": () => import("./kotlin/highlights.scm" as string, { with: { type: "file" } }),
  "kotlin/tree-sitter-kotlin.wasm": () => import("./kotlin/tree-sitter-kotlin.wasm" as string, { with: { type: "file" } }),
  "ruby/highlights.scm": () => import("./ruby/highlights.scm" as string, { with: { type: "file" } }),
  "ruby/tree-sitter-ruby.wasm": () => import("./ruby/tree-sitter-ruby.wasm" as string, { with: { type: "file" } }),
  "php/highlights.scm": () => import("./php/highlights.scm" as string, { with: { type: "file" } }),
  "php/tree-sitter-php.wasm": () => import("./php/tree-sitter-php.wasm" as string, { with: { type: "file" } }),
  "scala/highlights.scm": () => import("./scala/highlights.scm" as string, { with: { type: "file" } }),
  "scala/tree-sitter-scala.wasm": () => import("./scala/tree-sitter-scala.wasm" as string, { with: { type: "file" } }),
  "html/highlights.scm": () => import("./html/highlights.scm" as string, { with: { type: "file" } }),
  "html/tree-sitter-html.wasm": () => import("./html/tree-sitter-html.wasm" as string, { with: { type: "file" } }),
  "vue/highlights.scm": () => import("./vue/highlights.scm" as string, { with: { type: "file" } }),
  "vue/tree-sitter-vue.wasm": () => import("./vue/tree-sitter-vue.wasm" as string, { with: { type: "file" } }),
  "hcl/highlights.scm": () => import("./hcl/highlights.scm" as string, { with: { type: "file" } }),
  "hcl/tree-sitter-hcl.wasm": () => import("./hcl/tree-sitter-hcl.wasm" as string, { with: { type: "file" } }),
  "json/highlights.scm": () => import("./json/highlights.scm" as string, { with: { type: "file" } }),
  "json/tree-sitter-json.wasm": () => import("./json/tree-sitter-json.wasm" as string, { with: { type: "file" } }),
  "yaml/highlights.scm": () => import("./yaml/highlights.scm" as string, { with: { type: "file" } }),
  "yaml/tree-sitter-yaml.wasm": () => import("./yaml/tree-sitter-yaml.wasm" as string, { with: { type: "file" } }),
  "haskell/highlights.scm": () => import("./haskell/highlights.scm" as string, { with: { type: "file" } }),
  "haskell/tree-sitter-haskell.wasm": () => import("./haskell/tree-sitter-haskell.wasm" as string, { with: { type: "file" } }),
  "css/highlights.scm": () => import("./css/highlights.scm" as string, { with: { type: "file" } }),
  "css/tree-sitter-css.wasm": () => import("./css/tree-sitter-css.wasm" as string, { with: { type: "file" } }),
  "julia/highlights.scm": () => import("./julia/highlights.scm" as string, { with: { type: "file" } }),
  "julia/tree-sitter-julia.wasm": () => import("./julia/tree-sitter-julia.wasm" as string, { with: { type: "file" } }),
  "lua/highlights.scm": () => import("./lua/highlights.scm" as string, { with: { type: "file" } }),
  "lua/tree-sitter-lua.wasm": () => import("./lua/tree-sitter-lua.wasm" as string, { with: { type: "file" } }),
  "ocaml/highlights.scm": () => import("./ocaml/highlights.scm" as string, { with: { type: "file" } }),
  "ocaml/tree-sitter-ocaml.wasm": () => import("./ocaml/tree-sitter-ocaml.wasm" as string, { with: { type: "file" } }),
  "clojure/highlights.scm": () => import("./clojure/highlights.scm" as string, { with: { type: "file" } }),
  "clojure/tree-sitter-clojure.wasm": () => import("./clojure/tree-sitter-clojure.wasm" as string, { with: { type: "file" } }),
  "swift/highlights.scm": () => import("./swift/highlights.scm" as string, { with: { type: "file" } }),
  "swift/tree-sitter-swift.wasm": () => import("./swift/tree-sitter-swift.wasm" as string, { with: { type: "file" } }),
  "toml/highlights.scm": () => import("./toml/highlights.scm" as string, { with: { type: "file" } }),
  "toml/tree-sitter-toml.wasm": () => import("./toml/tree-sitter-toml.wasm" as string, { with: { type: "file" } }),
  "nix/highlights.scm": () => import("./nix/highlights.scm" as string, { with: { type: "file" } }),
  "nix/tree-sitter-nix.wasm": () => import("./nix/tree-sitter-nix.wasm" as string, { with: { type: "file" } }),
  "diff/highlights.scm": () => import("./diff/highlights.scm" as string, { with: { type: "file" } }),
  "diff/tree-sitter-diff.wasm": () => import("./diff/tree-sitter-diff.wasm" as string, { with: { type: "file" } }),
  "elixir/highlights.scm": () => import("./elixir/highlights.scm" as string, { with: { type: "file" } }),
  "elixir/tree-sitter-elixir.wasm": () => import("./elixir/tree-sitter-elixir.wasm" as string, { with: { type: "file" } }),
  "fsharp/highlights.scm": () => import("./fsharp/highlights.scm" as string, { with: { type: "file" } }),
  "fsharp/tree-sitter-fsharp.wasm": () => import("./fsharp/tree-sitter-fsharp.wasm" as string, { with: { type: "file" } }),
  "r/highlights.scm": () => import("./r/highlights.scm" as string, { with: { type: "file" } }),
  "r/tree-sitter-r.wasm": () => import("./r/tree-sitter-r.wasm" as string, { with: { type: "file" } }),
  "make/highlights.scm": () => import("./make/highlights.scm" as string, { with: { type: "file" } }),
  "make/tree-sitter-make.wasm": () => import("./make/tree-sitter-make.wasm" as string, { with: { type: "file" } }),
  "vim/highlights.scm": () => import("./vim/highlights.scm" as string, { with: { type: "file" } }),
  "vim/tree-sitter-vim.wasm": () => import("./vim/tree-sitter-vim.wasm" as string, { with: { type: "file" } }),
  "xml/highlights.scm": () => import("./xml/highlights.scm" as string, { with: { type: "file" } }),
  "xml/tree-sitter-xml.wasm": () => import("./xml/tree-sitter-xml.wasm" as string, { with: { type: "file" } }),
  "agda/highlights.scm": () => import("./agda/highlights.scm" as string, { with: { type: "file" } }),
  "agda/tree-sitter-agda.wasm": () => import("./agda/tree-sitter-agda.wasm" as string, { with: { type: "file" } }),
}

interface DefaultParserDescriptor {
  readonly filetype: string
  readonly aliases?: readonly string[]
  readonly queries: {
    readonly highlights: readonly string[]
    readonly injections?: readonly string[]
  }
  readonly wasm: string
  readonly injectionMapping?: InjectionMapping
}

const defaultParserDescriptors: readonly DefaultParserDescriptor[] = [
  {
    "filetype": "python",
    "queries": {
      "highlights": [
        "python/highlights.scm"
      ]
    },
    "wasm": "python/tree-sitter-python.wasm"
  },
  {
    "filetype": "rust",
    "queries": {
      "highlights": [
        "rust/highlights.scm"
      ]
    },
    "wasm": "rust/tree-sitter-rust.wasm"
  },
  {
    "filetype": "go",
    "queries": {
      "highlights": [
        "go/highlights.scm"
      ]
    },
    "wasm": "go/tree-sitter-go.wasm"
  },
  {
    "filetype": "cpp",
    "queries": {
      "highlights": [
        "cpp/highlights.scm"
      ]
    },
    "wasm": "cpp/tree-sitter-cpp.wasm"
  },
  {
    "filetype": "csharp",
    "queries": {
      "highlights": [
        "csharp/highlights.scm"
      ]
    },
    "wasm": "csharp/tree-sitter-c_sharp.wasm"
  },
  {
    "filetype": "bash",
    "queries": {
      "highlights": [
        "bash/highlights.scm"
      ]
    },
    "wasm": "bash/tree-sitter-bash.wasm"
  },
  {
    "filetype": "c",
    "queries": {
      "highlights": [
        "c/highlights.scm"
      ]
    },
    "wasm": "c/tree-sitter-c.wasm"
  },
  {
    "filetype": "java",
    "queries": {
      "highlights": [
        "java/highlights.scm"
      ]
    },
    "wasm": "java/tree-sitter-java.wasm"
  },
  {
    "filetype": "kotlin",
    "queries": {
      "highlights": [
        "kotlin/highlights.scm"
      ]
    },
    "wasm": "kotlin/tree-sitter-kotlin.wasm"
  },
  {
    "filetype": "ruby",
    "queries": {
      "highlights": [
        "ruby/highlights.scm"
      ]
    },
    "wasm": "ruby/tree-sitter-ruby.wasm"
  },
  {
    "filetype": "php",
    "queries": {
      "highlights": [
        "php/highlights.scm"
      ]
    },
    "wasm": "php/tree-sitter-php.wasm"
  },
  {
    "filetype": "scala",
    "queries": {
      "highlights": [
        "scala/highlights.scm"
      ]
    },
    "wasm": "scala/tree-sitter-scala.wasm"
  },
  {
    "filetype": "html",
    "queries": {
      "highlights": [
        "html/highlights.scm"
      ]
    },
    "wasm": "html/tree-sitter-html.wasm"
  },
  {
    "filetype": "vue",
    "queries": {
      "highlights": [
        "vue/highlights.scm"
      ]
    },
    "wasm": "vue/tree-sitter-vue.wasm"
  },
  {
    "filetype": "hcl",
    "queries": {
      "highlights": [
        "hcl/highlights.scm"
      ]
    },
    "wasm": "hcl/tree-sitter-hcl.wasm"
  },
  {
    "filetype": "json",
    "queries": {
      "highlights": [
        "json/highlights.scm"
      ]
    },
    "wasm": "json/tree-sitter-json.wasm"
  },
  {
    "filetype": "yaml",
    "queries": {
      "highlights": [
        "yaml/highlights.scm"
      ]
    },
    "wasm": "yaml/tree-sitter-yaml.wasm"
  },
  {
    "filetype": "haskell",
    "queries": {
      "highlights": [
        "haskell/highlights.scm"
      ]
    },
    "wasm": "haskell/tree-sitter-haskell.wasm"
  },
  {
    "filetype": "css",
    "queries": {
      "highlights": [
        "css/highlights.scm"
      ]
    },
    "wasm": "css/tree-sitter-css.wasm"
  },
  {
    "filetype": "julia",
    "queries": {
      "highlights": [
        "julia/highlights.scm"
      ]
    },
    "wasm": "julia/tree-sitter-julia.wasm"
  },
  {
    "filetype": "lua",
    "queries": {
      "highlights": [
        "lua/highlights.scm"
      ]
    },
    "wasm": "lua/tree-sitter-lua.wasm"
  },
  {
    "filetype": "ocaml",
    "queries": {
      "highlights": [
        "ocaml/highlights.scm"
      ]
    },
    "wasm": "ocaml/tree-sitter-ocaml.wasm"
  },
  {
    "filetype": "clojure",
    "queries": {
      "highlights": [
        "clojure/highlights.scm"
      ]
    },
    "wasm": "clojure/tree-sitter-clojure.wasm"
  },
  {
    "filetype": "swift",
    "queries": {
      "highlights": [
        "swift/highlights.scm"
      ]
    },
    "wasm": "swift/tree-sitter-swift.wasm"
  },
  {
    "filetype": "toml",
    "queries": {
      "highlights": [
        "toml/highlights.scm"
      ]
    },
    "wasm": "toml/tree-sitter-toml.wasm"
  },
  {
    "filetype": "nix",
    "queries": {
      "highlights": [
        "nix/highlights.scm"
      ]
    },
    "wasm": "nix/tree-sitter-nix.wasm"
  },
  {
    "filetype": "diff",
    "aliases": [
      "udiff",
      "patch"
    ],
    "queries": {
      "highlights": [
        "diff/highlights.scm"
      ]
    },
    "wasm": "diff/tree-sitter-diff.wasm"
  },
  {
    "filetype": "elixir",
    "queries": {
      "highlights": [
        "elixir/highlights.scm"
      ]
    },
    "wasm": "elixir/tree-sitter-elixir.wasm"
  },
  {
    "filetype": "fsharp",
    "queries": {
      "highlights": [
        "fsharp/highlights.scm"
      ]
    },
    "wasm": "fsharp/tree-sitter-fsharp.wasm"
  },
  {
    "filetype": "r",
    "queries": {
      "highlights": [
        "r/highlights.scm"
      ]
    },
    "wasm": "r/tree-sitter-r.wasm"
  },
  {
    "filetype": "make",
    "aliases": [
      "makefile"
    ],
    "queries": {
      "highlights": [
        "make/highlights.scm"
      ]
    },
    "wasm": "make/tree-sitter-make.wasm"
  },
  {
    "filetype": "vim",
    "queries": {
      "highlights": [
        "vim/highlights.scm"
      ]
    },
    "wasm": "vim/tree-sitter-vim.wasm"
  },
  {
    "filetype": "xml",
    "queries": {
      "highlights": [
        "xml/highlights.scm"
      ]
    },
    "wasm": "xml/tree-sitter-xml.wasm"
  },
  {
    "filetype": "agda",
    "queries": {
      "highlights": [
        "agda/highlights.scm"
      ]
    },
    "wasm": "agda/tree-sitter-agda.wasm"
  }
]

export const defaultParserAssetPaths: readonly string[] = [
  ...new Set(
    defaultParserDescriptors.flatMap((parser) => [
      ...parser.queries.highlights,
      parser.wasm,
      ...(parser.queries.injections ?? []),
    ]),
  ),
]

let cachedParsers: Promise<FiletypeParserOptions[]> | undefined

export function getParsers(): Promise<FiletypeParserOptions[]> {
  cachedParsers ??= Promise.all(defaultParserDescriptors.map(resolveDefaultParser))
  return cachedParsers
}

async function resolveDefaultParser(parser: DefaultParserDescriptor): Promise<FiletypeParserOptions> {
  const queries: FiletypeParserOptions["queries"] = {
    highlights: await Promise.all(parser.queries.highlights.map(resolveParserAsset)),
  }
  if (parser.queries.injections) {
    queries.injections = await Promise.all(parser.queries.injections.map(resolveParserAsset))
  }

  return {
    filetype: parser.filetype,
    ...(parser.aliases ? { aliases: [...parser.aliases] } : {}),
    queries,
    wasm: await resolveParserAsset(parser.wasm),
    ...(parser.injectionMapping ? { injectionMapping: parser.injectionMapping } : {}),
  }
}

function resolveParserAsset(relativePath: string): Promise<string> {
  const loadBundledFile = bundledAssetLoaders[relativePath]
  if (!loadBundledFile) {
    throw new Error(`Unknown parser asset: ${JSON.stringify(relativePath)}`)
  }
  return resolveBundledFilePath(
    relativePath,
    loadBundledFile,
    new URL(`./${relativePath}`, import.meta.url),
    import.meta.url,
    { loadBundledFileFallback: true, useAssetRoot: false },
  )
}
