import type { SessionStatusItem } from '@config/session-layout.ts'

export const LOADING_VERBS: Array<string> = [
  'excruciating',
  'vibing',
  'cooking',
  'cogitating',
  'ruminating',
  'scheming',
  'conjuring',
  'marinating',
  'simmering',
  'brewing',
  'manifesting',
  'noodling',
  'pondering',
  'deliberating',
  'galaxy-braining',
  'daydreaming',
  'plotting',
  'spelunking',
  'transmuting',
  'synthesizing',
  'musing',
  'percolating',
  'whirring',
  'computing',
  'triangulating',
  'extrapolating',
  'brainstorming',
  'obsessing',
  'spiraling',
  'tunneling',
  'wrangling',
  'juggling',
  'untangling',
  'deciphering',
  'divining',
  'dowsing',
  'scrying',
  'channeling',
  'invoking',
  'incanting',
  'distilling',
  'crystallizing',
  'fermenting',
  'caramelizing',
  'whisking',
  'kneading',
  'proofing',
  'schematizing',
  'actualizing',
  'rhapsodizing',
  'hacking',
  'djing',
]

export const pickLoadingVerb = (): string => LOADING_VERBS[Math.floor(Math.random() * LOADING_VERBS.length)] ?? 'thinking'

export const isLoadingAdjacentToAgent = (previousItem: SessionStatusItem | undefined): boolean => previousItem === 'agent'
